/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class logic_Controller */

#ifndef _Included_logic_Controller
#define _Included_logic_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     logic_Controller
 * Method:    sendSamples
 * Signature: (Ltda/Nodo;Llogic/Controller;)Ltda/Nodo;
 */
JNIEXPORT jobject JNICALL Java_logic_Controller_sendSamples
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
